In [72]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree

In [73]:
df = pd.read_csv("titanic.csv")

In [74]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [75]:
inputs = df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked","Survived"],axis=1)

In [76]:
target = df["Survived"]

In [77]:
inputs.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [78]:
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# DATA PREPROCESSING

In [79]:
inputs["Age"].fillna(df["Age"].mean(),inplace=True)
inputs["Sex"].fillna(df["Sex"].mode(),inplace=True)
inputs["Pclass"].fillna(df["Pclass"].mode(),inplace=True)

In [80]:
from sklearn.preprocessing import LabelEncoder

In [81]:
Pclass_le = LabelEncoder()
Sex_le = LabelEncoder()
Age_le = LabelEncoder()

In [82]:
inputs["Pclass_n"] = Pclass_le.fit_transform(inputs["Pclass"]);
inputs["Sex_le"] = Sex_le.fit_transform(inputs["Sex"]);
inputs["Age_le"] = Age_le.fit_transform(inputs["Age"]);

In [83]:
inputs.head()

Pclass     Sex   Age     Fare  Pclass_n  Sex_le  Age_le
0       3    male  22.0   7.2500         2       1      28
1       1  female  38.0  71.2833         0       0      52
2       3  female  26.0   7.9250         2       0      34
3       1  female  35.0  53.1000         0       0      48
4       3    male  35.0   8.0500         2       1      48

In [84]:
inputs = inputs.drop(["Sex","Age","Pclass"],axis=1)
inputs

Fare  Pclass_n  Sex_le  Age_le
0     7.2500         2       1      28
1    71.2833         0       0      52
2     7.9250         2       0      34
3    53.1000         0       0      48
4     8.0500         2       1      48
..       ...       ...     ...     ...
886  13.0000         1       1      35
887  30.0000         0       0      24
888  23.4500         2       0      39
889  30.0000         0       1      34
890   7.7500         2       1      43

[891 rows x 4 columns]

In [58]:
train_X,train_y,test_X,test_Y = train_test_split(target,inputs,test_size=.2)

In [63]:
model = tree.DecisionTreeClassifier()

In [70]:
model.fit(inputs,target)

DecisionTreeClassifier()

In [89]:
model.predict([[7.2500,2,1,28]])

/Users/ruslanbabar/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [90]:
model.predict([[71.2833,0,0,52]])

/Users/ruslanbabar/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [91]:
model.predict([[7.9250,2,0,34]])

/Users/ruslanbabar/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])