# Linear Regression
- Continuous Data

# Classification
- Categorical Data

Solution

# Logictic Regression

- Binary Classification
- Multiclass classification


Binary logistic regression: In this approach, the response or dependent variable is dichotomous in nature—i.e. it has only two possible outcomes (e.g. 0 or 1). Some popular examples of its use include predicting if an e-mail is spam or not spam or if a tumor is malignant or not malignant.



In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math
from sklearn  import model_selection

In [127]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [128]:
model = linear_model.LogisticRegression()

In [129]:
model.fit(df[["age"]],df.bought_insurance)

LogisticRegression()

In [130]:
age1 = 10
age2 = 45

In [131]:
model.predict([[age1]])

/Users/ruslanbabar/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [132]:
model.predict([[age2]])

/Users/ruslanbabar/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [146]:
X_ = df[["age"]]

In [162]:
y_ = df[["bought_insurance"]]

In [168]:
X_train_,X_test_,y_train_,y_test_ = model_selection.train_test_split(X,y,test_size=.2)

In [169]:
model.fit(X_train_,y_train_)

LogisticRegression()

In [170]:
model.predict(X_test_)

array([1, 1, 1, 0, 1, 1])

In [171]:
y_test_

23    1
5     1
15    1
26    0
24    1
4     1
Name: bought_insurance, dtype: int64

In [167]:
model.score(X_test_,y_test_)

0.9090909090909091

In [172]:
model.predict_log_proba(X_test_)

array([[-0.88742542, -0.5305427 ],
       [-1.79009203, -0.18265538],
       [-1.6963063 , -0.20255637],
       [-0.11078866, -2.25501382],
       [-1.25921812, -0.3339018 ],
       [-0.95585967, -0.48529023]])